#!/bin/bash

source "$CONFIG_DIR/colors.sh"

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

bar=(
  position=left
  height=42
  margin=10
  corner_radius=12
  blur_radius=30
  color=$BAR_COLOR
  display=main
  y_offset=10
  padding_right=4
  padding_left=4
)

sketchybar --bar "${bar[@]}"
##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  icon.font="SF Pro:Bold:17.0"
  label.font="SF Pro:Bold:14.0"
  icon.color=$TEXT_COLOR
  label.color=$TEXT_COLOR
  background.color=$WIDGET_BG
  background.corner_radius=8
  background.height=34
  width=34
  icon.padding_left=5
  icon.padding_right=5
  icon.align=center
)
sketchybar --default "${default[@]}"

display_count=$(aerospace list-monitors --count)
ui_display_count=1

while [ "$ui_display_count" -le "$display_count" ]; do
  # Monitor icon
  sketchybar --add item "mon.$ui_display_count" center \
    --set "mon.$ui_display_count" \
    icon="􀢹"
  # Spaces
  for sid in $(aerospace list-workspaces --monitor "$ui_display_count"); do

    sketchybar --add item "sep.$ui_display_count.$sid" center \
      --set "sep.$ui_display_count.$sid" \
      width=8 \
      background.color=$BAR_COLOR

    sketchybar --add item "space.$ui_display_count.$sid" center \
      --set "space.$ui_display_count.$sid" \
      icon="$sid"

  done

  # Separator (except after last display)
  if [ "$ui_display_count" -lt "$display_count" ]; then
    sketchybar --add item "sep.$ui_display_count" center \
      --set "sep.$ui_display_count" \
      width=12 \
      background.color=$BAR_COLOR
  fi

  ui_display_count=$((ui_display_count + 1))
done

sketchybar --update
