#!/bin/bash

BAR_COLOR=0xff1F0142
ACTIVE_BG=0xff9252d5
ITEM_BG=0x14EED8FF
BORDER_COLOR=0x20EED8FF
TEXT_COLOR=0xffEED8FF

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

bar=(
  position=left
  height=52
  margin=10
  corner_radius=12
  blur_radius=30
  border_color=$BORDER_COLOR
  border_width=2
  color=$BAR_COLOR
  display=main
  y_offset=10
  padding_right=6
  blur_radius=8
  padding_left=6
)

sketchybar --bar "${bar[@]}"
##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  icon.font="SF Pro:Bold:17.0"
  label.font="SF Pro:Bold:14.0"
  icon.color=$TEXT_COLOR
  label.color=$TEXT_COLOR
  background.color=$ITEM_BG
  background.border_color=$BORDER_COLOR
  background.border_width=2
  background.corner_radius=6
  background.height=34
  width=34
  icon.padding_left=5
  icon.padding_right=5
  icon.align=center
)
sketchybar --default "${default[@]}"

sketchybar --add event aerospace_workspace_change

# Spaces
for sid in $(aerospace list-workspaces --all); do

  sketchybar --add item "sep.$sid" center \
    --set "sep.$sid" \
    width=8 \
    background.color=$BAR_COLOR \
    background.border_width=0

  sketchybar --add item "space.$sid" center \
    --subscribe "space.$sid" aerospace_workspace_change \
    --set "space.$sid" \
    icon="$sid" \
    background.color=$ITEM_BG script="$PLUGIN_DIR/aerospace.sh $sid"

done

sketchybar --update
