#!/bin/bash

BAR_COLOR=0xff1F0142
ACTIVE_BG=0xff9252d5
ITEM_BG=0x14EED8FF
BORDER_COLOR=0x20EED8FF
TEXT_COLOR=0xffEED8FF
TRANSPARENT=0x00fffff

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

bar=(
  position=left
  height=60
  margin=10
  corner_radius=12
  blur_radius=30
  border_color=$BORDER_COLOR
  border_width=2
  color=$BAR_COLOR
  display=main
  y_offset=10
  padding_left=12
  padding_right=12
  font_smoothing=on
)

sketchybar --bar "${bar[@]}"
##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  icon.font="SF Pro"
  label.font="SF Pro"
  icon.font.size=14
  label.font.size=14
  icon.color=$TEXT_COLOR
  label.color=$TEXT_COLOR
  label.font.style=Bold
  background.color=$ITEM_BG
  background.border_color=$BORDER_COLOR
  background.border_width=2
  background.corner_radius=6
  background.height=36
  y_offset=10
)
sketchybar --default "${default[@]}"

# Top Items

sketchybar --add item clock left \
  --set clock \
  update_freq=10 \
  background.color=$TRANSPARENT \
  background.border_color=$TRANSPARENT \
  label.padding_right=8 \
  label.padding_left=8 \
  icon.drawing=off \
  label.align="center" \
  script="$PLUGIN_DIR/clock.sh"

sketchybar --add item sep1 left \
  --set sep1 \
  background.color=$TRANSPARENT \
  background.height=2 \
  padding_left=12 \
  padding_right=12 \
  label="───" \
  label.color=$BORDER_COLOR

sketchybar --add item day left \
  --set day \
  update_freq=10 \
  background.color=$TRANSPARENT \
  background.border_color=$TRANSPARENT \
  padding_right=8 \
  padding_left=8 \
  label.padding_right=8 \
  label.padding_left=8 \
  background.height=14 \
  label.align="center" \
  label="$(date "+%a")"
sketchybar --add item date left \
  --set date \
  update_freq=10 \
  background.color=$TRANSPARENT \
  background.border_color=$TRANSPARENT \
  padding_right=8 \
  label.padding_right=8 \
  label.padding_left=8 \
  background.height=14 \
  label.align="center" \
  label="$(date "+%d")"

sketchybar --add item month left \
  --set month \
  update_freq=10 \
  background.color=$TRANSPARENT \
  background.border_color=$TRANSPARENT \
  padding_right=8 \
  label.padding_right=8 \
  label.padding_left=8 \
  background.height=14 \
  label.align="center" \
  label="$(date "+%b")"

sketchybar --add item sep2 left \
  --set sep2 \
  background.color=$TRANSPARENT \
  background.height=2 \
  padding_left=12 \
  padding_right=12 \
  label="───" \
  label.color=$BORDER_COLOR

sketchybar --add event aerospace_workspace_change

# Spaces
for sid in $(aerospace list-workspaces --all); do

  sketchybar --add item "sep.$sid" left \
    --set "sep.$sid" \
    width=8 \
    background.color=$BAR_COLOR \
    background.border_width=0

  sketchybar --add item "space.$sid" left \
    --subscribe "space.$sid" aerospace_workspace_change \
    --set "space.$sid" \
    icon="$sid" \
    icon.align="center" \
    icon.padding_left=14 \
    icon.padding_right=14 \
    background.color=$ITEM_BG \
    width=36 \
    script="$PLUGIN_DIR/aerospace.sh $sid"

done

sketchybar --update
